import Carousel from "@components/Carousel";
import Footer from "@components/Footer";
import JoinUs from "@components/JoinUs";
import ListClient from "@components/ListClient";
import Navbar from "@components/Navbar";
import Product from "@components/Product";
import Profile from "@components/Profile";
import Story from "@components/Story";
import UpcomingClass from "@components/UpcomingClass";
import VideoBackground from "@components/VideoBackground";
import { Close } from "@mui/icons-material";
import { Box, Dialog, IconButton, Modal, Typography } from "@mui/material";
import Head from "next/head";
import { useState } from "react";

export default function Home() {
  const [showDialog, setShowDialog] = useState(true);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Carousel />
      <Profile />
      <ListClient />
      <Product />
      <VideoBackground />
      <UpcomingClass />
      <Story />
      <Footer />
      <JoinUs />
      <Dialog open={showDialog}>
        <Box sx={{ textAlign: "right", width: "100%" }}>
          <IconButton onClick={() => setShowDialog(false)}>
            <Close />
          </IconButton>
        </Box>
        <Box
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            height: "100%",
          }}
        >
          <Typography id="modal-modal-title">Ads Here...</Typography>
        </Box>
      </Dialog>
    </>
  );
}
